### ISSUE TITLE
Migration from very old official synology package (11.8)

### ISSUE THREAD

**Issue by digitalwannabe** [jboxberger/synology-gitlab-ce#13]
i'm trying for days to update an old gitlab installation, so i can switch to this repo and upgrade to dsm7. For this I'm trying to arrive at version 12.10.6, the lowest version available here.

Unfortunately updating the official synology package to 12.10.6 doesn't work, as it requires a postresql update from 10 to 11 and the bionic release of postresql has been moved to an archive, and even if i change this in the sources.list file the upgrade will fail, as it will download a new image and create a new container reversing any changes.

I successfully upgraded up until 12.4.2 using the predecessor of this package from @jboxberger (non ce version), 12.9 i can run, see projects, commits, etc. but it won't load actual blob data. Upgrade to 12.10.6 fails.

so i tried to build this repo for 12.0.3 or 12.4.2, which installs fine, but the container stops after a few minutes
![grafik](https://github.com/jboxberger/synology-gitlab-ce/assets/7549101/14fdbdc9-ea6e-4c65-a6be-0f2e8412bb16)

i have also tried installing 12.10.6 from this repo and downgrade to 12.4.2 or 12.0.3, same errors....

It's not a huge gitlab server, I am ready to export groups and projects and import in another instance, but for this i would have to come as close as 2 minor versions to 12.10.6, which i simply can't manage to do.

i don't know much about any of this, any help would be greatly appreciated!

**Comment by jboxberger** [comment]
Hi, the 10.x-12.x were really messy then and the postgres migration was really pain in the a**. 

I think the best way for you is to migrate to the "-ce" package and upgrade from then.
1) Install the "[Advanced](https://github.com/jboxberger/synology-gitlab-ce?tab=readme-ov-file#advanced)" Package with the same version as you current stable gitlab Version (they can run concurrent). Just modify the vesion and the folder in the command shown at the end of setup.
![image](https://github.com/jboxberger/synology-gitlab-ce/assets/1545845/83c8796f-7501-43ee-b57f-fe162f81e955)

2) Export and migrate the repositories and data to the "-ce".

3) Once you're done use this upgrade path tool (https://gitlab-com.gitlab.io/support/toolbox/upgrade-path/?edition=ce) to update to the desired version. I know it sucks but i recommend to test each version because if at the end of the Upgrade something is broken you do not really know at which version i broke. So you have to start from the beginning to identify the breaking release and troubleshoot it.

4) If everything went fine and test are successful you can kill your old gitlab, if not you can start over. 

With this method you do not risc your data becaus you do not modify the original gitlab installation. 

Hope i was able to help you. 
Kind Regards

**Comment by digitalwannabe** [comment]
Thank you for the fast reply - and sorry if I was not being clear: after reading similar issues here I also came to the conclusion it would be best to switch to -ce asap, my problem is I can't reach a matching version. Using the official synology package I can only get to 11.11.8, using your synology-gitlyb package I can upgrade to 12.0.3 and 12.4.2 - however, I can't install the -ce package for 11.11.8, 12.0.3 or 12.4.2. I have tried building my own spk as described in the readme, and I have tried downgrading from 12.10.6, both attempts install and start a container then fail to run (screenshot above) :|

**Comment by jboxberger** [comment]
I i will try to build one on my VM. Which DSM and current stable Gitlab ( version you will export your repos from) do you have?

**Comment by jboxberger** [comment]
i am happy to help. So basically you have them both running parallel and can migrate to the 12.0.3-ce instance? So is there a todo for me left? Can i help you with something at the moment?

**Comment by digitalwannabe** [comment]
sorry again for not being clear -  i can't install 12.0.3-ce, I have a backup of my standard 12.0.3 prepared to be restored in -ce

**Comment by jboxberger** [comment]
I can build and install the 12.0.3  package without issues.

Assuming you "non-ce" package is at 12.0.3
1) Uninstall an delete all "-ce" packages you installed before.
2) install the spk int this zip file
[synology-gitlab-ce-12.0.3-dsm.zip](https://github.com/jboxberger/synology-gitlab-ce/files/15227346/synology-gitlab-ce-12.0.3-dsm.zip)
3) login to your DSM over SSH and execute, please check the ports are not already used and modify if needed:
```
cd /var/packages/synology-gitlab-ce/scripts && \
sudo sh gitlab install synology-gitlab-ce \
--version=12.0.3-ce.0 \
--share=synology-gitlab-ce \
--port-ssh=30022 \
--port-http=30080 \
--port-https=30443
```
4) export the data from your 12.0.3 synology-giltab package and import it to 12.0.3 synology-giltab-ce like [here](https://github.com/jboxberger/synology-gitlab-ce?tab=readme-ov-file#migration-from-synology-gitlab-package). 

If you have SSL errors during install "error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker" have a look [here](https://xpenology.com/forum/topic/49308-how-to-update-lets-encrypt-root-certificate/). This shows the whole process but this command should help, warning it reboots automatically your system.
```
sudo -i && cp /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt.ORIG && curl -k "https://letsencrypt.org/certs/isrgrootx1.pem" >> /etc/ssl/certs/ca-certificates.crt && reboot 
```
Sorry for the late reply, a had to sole the SSL error before.

**Comment by digitalwannabe** [comment]
Thank you again for your time.

Unfortunately, I end at the same result as with my version of the 12.0.3-ce package. Everything downloads fine running the script, but the container stops on the first run due to errors :(

[Here](https://github.com/jboxberger/synology-gitlab-ce/files/15234306/synology-gitlab-ce.zip) is the log file. It looks like it has a problem with database migration, which is weird since it's a fresh install. I can't get any other clues from it, but I'm also a noob in all of this :| do you have any idea what could be wrong?

thank you!

**Comment by jboxberger** [comment]
have you also deleted the docker/synology-gitlab-ce folder? if not the, DB file still remains there and wehn you prevously installed the 12.4.3 then mybe this causes the problem.
