### ISSUE TITLE
unclear install instructions

### ISSUE THREAD

**Issue by caco3** [jboxberger/synology-gitlab-ce#4]
The wizard says that one needs to run the ssh cmd after the installation completes.

On its last page, the wizard has a tick box to directly start the package afterwards. I guess this has no effect but clarification would be great

**Comment by jboxberger** [comment]
Yes you're guessing right. the checkbox comes from DSM itself and starts/stops the package, but not the container. In the classic package the package itself and container is bundled, stopping the package stops the container, in the advanced version they are apart and there is no way to control the container from the start-stop script. You need root/admin priveleges to control the docker container. But since DSM7 you can not install priviliged packages, they run only within an separate user with limited priveleges and the start-stop script fail due lack of permssions. This was hard to find a way around. Within the advanced package the start-stop only handle the presence of the GitLab CE Icon in the DSM Menu. If you stop the package, its gone, if you start it, its there. 

I thing a clarification here would confuse the people and i think its intuitive enough. Everybody would try to start the package intuitively and therefore will succeed. If something is wrong, i assume, they will check if the package is running and also start it, if its not.

I have no clue how to clarify it without more confusion :-)
